#!/bin/sh /etc/rc.common

START=56

start()
{
	gdisplay=$(uci get gargoyle.display.system_tinyproxy 2>/dev/null)
	if [ -z "$gdisplay" ] ; then
		uci set gargoyle.display.system_tinyproxy='Tinyproxy'
		uci set gargoyle.scripts.system_tinyproxy='tinyproxy.sh'
		uci set gargoyle.system.tinyproxy='352'
		uci commit
	fi
}
